### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by sercanarici** [MobileUI/mobileui#8]
Node version: 12.3.1
npm version: 6.12.1

**When installing it says:**

`PS C:\Users\sercan> npm install -g mobileui
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ supp
ort 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it
, and update to graceful-fs@4.x.
C:\Users\sercan\AppData\Roaming\npm\mobileui -> C:\Users\sercan\AppData\Roaming\npm\node_modules\mobileui\bin\mobileui
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\mobileui\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})`

**When try to run it says**

`
PS C:\Users\sercan> mobileui
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\sercan\AppData\Roaming\npm\node_modules\mobileui\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\sercan\AppData\Roaming\npm\node_modules\mobileui\node_modules\natives\index.js:
55:10)
    at Object.<anonymous> (C:\Users\sercan\AppData\Roaming\npm\node_modules\mobileui\node_modules\fstream\node_modules\g
raceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
`

**Comment by luke-lewandowski** [comment]
@sercanarici - hey were you ever able to resolve it. So far I have only found that it could be due to node version. Trying it now.

**Comment by fabiorogeriosj** [comment]
I solved it, updated the libs! New life!
